ca-risken/aws

Makefile
env_sample.sh
src/access-analyzer/Dockerfile
src/activity/Dockerfile
src/admin-checker/Dockerfile
src/aws/Dockerfile
src/cloudsploit/Dockerfile
src/guard-duty/Dockerfile
src/portscan/Dockerfile

rm: GOPRIVATE

---

src/admin-checker/go.mod
src/admin-checker/go.sum
src/admin-checker/main.go
src/cloudsploit/go.mod
src/cloudsploit/go.sum
src/cloudsploit/main.go
src/portscan/go.mod
src/portscan/go.sum
src/portscan/main.go

スキャン失敗時のユーザ通知処理を追加します。
ただし、一旦GuardDutyとAccessAnalyzerは外します。

add: finalizer

---

src/cloudsploit/recommend.go

プラグイン名が存在しないWARNが出ていてrecommend登録できてなかったので修正します

fix: plugin name

---

src/cloudsploit/finding.go
src/cloudsploit/go.mod
src/cloudsploit/go.sum

CloudSploitのFinding登録をPutFindingBatch APIを利用するように変更します

fix: use PutFindingBatch API

---

src/portscan/finding.go
src/portscan/go.mod
src/portscan/go.sum

finding登録処理に時間がかかっているのでパフォーマンス改善目的でBatch APIを利用するようにします。

fix: use batch api(portscan)

---

src/cloudsploit/main.go
src/guard-duty/main.go

fix: core addr

---

src/aws/service.go

現時点で握りつぶしているエラーがあるが、情報が少なく調査が難しいためログを追加

Add error log info

---

src/access-analyzer/main.go

alertサーバが残ってしまっていたため削除します（core統合文脈）

rm: alert server

---

src/guard-duty/main.go

guarddutyのスキャンエラー時にユーザ通知する実装を入れます。

add: finalyzer

---

src/aws/service.go

スキャンすべき対象へのスキャン要求がなされていない可能性がある場合に、エラーを返すよう修正

return error when fail processing invoke scan

---

src/portscan/go.mod
src/portscan/go.sum

以下の修正を反映させます
https://github.com/ca-risken/common/pull/111

update portscan module

---

src/activity/client.go
src/activity/cloudtrail.go
src/activity/cloudtrail_test.go
src/activity/config.go
src/activity/config_test.go
src/activity/main.go
src/activity/service.go

src/activity配下のエラーハンドリング改善しました。

Resolve missing error in activity

---

src/portscan/go.mod
src/portscan/go.sum
src/portscan/portscan.go

Logging portscan result analysis failure

---

Makefile
go.work
go.work.sum

add: go workspace

---

cmd/cloudsploit/main.go
pkg/cloudsploit/cloudsploit.go
pkg/cloudsploit/handler.go

cloudsploitでスキャン時にpanicが起こる事象が発生しました。
そのバグ修正になります

fix: cloudsploit bug

---

pkg/cloudsploit/cloudsploit.go

まれにスキャン結果のJSONパースエラーが発生(再実行時は再現しないエラー)してしまうためエラーログに情報追加します。
```
Failed to parse scan results. error: unexpected end of JSON input
```

add: error log

---

pkg/cloudsploit/plugin_finding_map.go
pkg/cloudsploit/recommend.go

CloudSploit アップデートにともなってプラグインに対するレコメンドを追加します

add: recommendations

---

pkg/cloudsploit/plugin_finding_map.go

fix: score

---

cmd/access-analyzer/main.go
cmd/admin-checker/main.go
cmd/cloudsploit/main.go
cmd/guard-duty/main.go
cmd/portscan/main.go

fix: datasource api

---

cmd/access-analyzer/main.go
cmd/admin-checker/main.go
cmd/cloudsploit/main.go
cmd/guard-duty/main.go
cmd/portscan/main.go

scanエラー通知の方針を変えるため、Finalyzerの処理を外します

fix: finalyzer

---

pkg/adminchecker/admin_checker.go
pkg/adminchecker/handler.go
pkg/adminchecker/handler_test.go

コンソールログインができない＆有効なアクセスキーが存在しないIAMユーザはスコアを下げるロジックを追加します。
その他、refactor & typo修正です。

Fix scan error

---

go.mod
go.sum
pkg/accessanalyzer/accessanalyzer.go
pkg/accessanalyzer/accessanalyzer_test.go

SNSとSQSのリソースはConditionの詳細を取得する処理を追加します。

add: condition analyze

---

pkg/cloudsploit/plugin_finding_map.go

ssmDocumentPublicAccessのスコアを変更したいです。
内容的にはS3のパブリックアクセスブロックと同じかと思いますので、そちらにあわせて0.3でどうでしょうか？

fix: ssmDocumentPublicAccess score

---

cmd/cloudsploit/main.go
pkg/cloudsploit/finding_test.go
pkg/cloudsploit/handler.go
pkg/cloudsploit/setting.go
pkg/cloudsploit/setting_test.go

任意のcloudsploit.yamlを注入できるようにします

support: cloudsploit setting yaml from other path

---

pkg/cloudsploit/cloudsploit.go
pkg/cloudsploit/cloudsploit_test.go

fix: cloudsploit ignore plugin

---

dockers/cloudsploit/README.md

add: upgrade manual

---

pkg/cloudsploit/cloudsploit.go

スキャン速度改善でSecurityGroupのAPIコールを減らします

fix: cloudsploit metadata

---

codebuild/multi-arch/buildspec-batch.yml

AL2 -> AL2023移行のためビルドイメージ更新します

upgrade: build runtime

---

cmd/cloudsploit/main.go
dockers/access-analyzer/Dockerfile
dockers/admin-checker/Dockerfile
dockers/cloudsploit/Dockerfile
dockers/guard-duty/Dockerfile
dockers/portscan/Dockerfile
pkg/cloudsploit/cloudsploit.go

CloudSploitの並列数をパラメータ化します。
また、Dockerビルド時にWARNが出るようになったので `as` -> `AS` に修正

add: parallel param

---

pkg/cloudsploit/cloudsploit.go

特定のAWSアカウントでスキャンが終わらない状態のまま残り続ける問題を確認しています。
一部のプラグインであまりにも時間がかかりすぎているスキャンに対してはタイムアウトを設定したいです。
（タイムアウトしたプラグインはWARNログに出力）
タイムアウトの設定によって、
- 一部のアカウントが終わらない状態を回避して全体影響を軽減
- 問題のアカウントとプラグインを特定

fix: handle scan timeout

---

pkg/cloudsploit/cloudsploit.go

fix: scan timeout

---

cmd/cloudsploit/main.go
pkg/cloudsploit/cloudsploit.go

fix: scan timeout param

---

.github/workflows/build-pr-aws.yml

.githubのreusableワークフロー変更に伴う修正です

del: test_cmd
