src/cloudsploit/config.go

AssumeRoleのセッションが1時間以上設定できない仕様になっているため、RISKEN側もあわせて修正します
https://docs.aws.amazon.com/ja_jp/IAM/latest/UserGuide/id_roles_terms-and-concepts.html
> ロールの連鎖
ロールの連鎖は、AWS CLI または API を使用して 2 つ目のロールを引き受けるロールを使用する場合に発生します。
(中略)
ロールの連鎖では、AWS CLI または AWS API ロールセッションは最長 1 時間に制限されます。[AssumeRole](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html) 
(中略)
ロールの連鎖を使用してロールを引き受ける場合、DurationSeconds パラメータ値で 1 時間を超える値を指定すると、オペレーションは失敗します
関連: https://github.com/ca-risken/internal-community/issues/188

fix: session duration

---

src/cloudsploit/Dockerfile
src/cloudsploit/cloudsploit.go
src/cloudsploit/handler.go
src/cloudsploit/main.go

PodのメモリLimitを使い切る前にJavascriptのメモリのヒープサイズ上限に達していたので、オプションでメモリ量を指定できるようにします
e.g.)
```shell
MAX_MEM_SIZE_MB=2048 # (2GB)
```
- [メモリオプション(公式リファレンス)](https://nodejs.org/api/cli.html#--max-old-space-sizesize-in-megabytes)
- [versionごとのheapサイズのデフォルト値](https://medium.com/geekculture/node-js-default-memory-settings-3c0fe8a9ba1)

add: memory size option

---

src/cloudsploit/handler.go

CloudSploitのスキャンに時間がかかる場合があり、ボトルネックがどこか調査したいのでログを追加します

add: scan log

---

src/portscan/handler.go
src/portscan/portscan.go
src/portscan/portscan_test.go

スキャン並列化の前段として、全Regionからスキャン対象を取得した後にスキャンを実行するよう変更します

fix-portscan

---

src/cloudsploit/finding.go
src/cloudsploit/go.mod
src/cloudsploit/go.sum

パフォーマンス向上の目的でResourceの登録処理をPutResrouceBatch API方式に変更します
（PutResrouceBatch呼び出しの並列化はパフォーマンスの改善状況やDBの負荷状況などの様子を見てから判断する想定です）

fix: use PutResrouceBatch API

---

src/cloudsploit/main.go

close https://github.com/ca-risken/internal-community/issues/241
CloudSploitのオプションでMaxMemSizeMBのデフォルト値指定が漏れいていました。この指定がないと起動時にエラーが発生していたためデフォルト値設定します。（0を指定するとサーバ上のデフォルトのJavascriptのヒープサイズで起動する挙動になります）

fix: default MaxMemSizeMB

---

src/portscan/portscan.go

close https://github.com/ca-risken/internal-community/issues/252
public IP を持たないlightsail インスタンスがあったときにpanicが発生していた模様。

fix: nil pointer exception

---

src/admin-checker/admin_checker.go
src/admin-checker/handler.go
src/admin-checker/main.go

admin-checkerのRetryerのオプション設定を追加します。
IAM関連のAPIはRateLimitが厳しく、アプリケーションをスケールアウトするとエラーが発生しやすいため、リトライ値を調整できるようにする意図です
https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/retries-timeouts/

add: RetryMaxAttempts

---

src/access-analyzer/main.go

access analyzerのスキャンに失敗した際のユーザ通知処理です。
ref https://github.com/ca-risken/internal-community/issues/240

add: finalyzer for access analyzer

---

src/cloudsploit/plugin_finding_map.go

rdsPubliclyAccessibleのスコアを修正します。
こちらの設定がされていても実際はセキュリティグループで保護されている場合があります。
また、aws:portscan側でインターネットからアクセス可能かを検知しており、より明確なリスクとして検知できるため、こちらのプラグインのスコアを調整します。

fix: rdsPubliclyAccessible score

---

src/access-analyzer/accessanalyzer.go
src/access-analyzer/client.go
src/access-analyzer/handler.go
src/access-analyzer/main.go
src/access-analyzer/sqs.go

src/accecc-analyzer配下のエラーハンドリング改善しました。
* `handleErrorWithUpdateStatus`はステータスの更新とエラーのラッピングという二つの責務を持っていたので、見通しをよくするために分割しました。責務に合わせてメソッド名も変更しています。
* `accessAnalyzerClient.getAccessAnalyzer`の処理で`listFindings`に失敗した時にエラーを返していませんでしたが、想定しているケース以外でエラーが発生すると想定しているスキャンができないためエラーを返すようにしています。その場合、ユーザがリトライしてもスキャンができない可能性があるため、通知ログを出してこちらで検知できるようにしています。

Resolve missing error in access analyzer

---

src/admin-checker/admin_checker.go
src/admin-checker/client.go
src/admin-checker/handler.go
src/admin-checker/main.go
src/admin-checker/sqs.go

src/admin-checker配下のエラーハンドリング改善しました。
* client生成時のエラーは呼び出し元でハンドリングするために呼び出し元に返すようにしました。
* handleErrorWithUpdateStatusはステータスの更新とエラーのラッピングという二つの責務を持っていたので、見通しをよくするために分割しました。責務に合わせてメソッド名も変更しています。
* analyzeServicceAccessDetailsの処理がエラーになる場合、呼び出し元でエラーを返すように変更しました。

Resolve missing error in admin checker

---

src/cloudsploit/client.go
src/cloudsploit/config.go
src/cloudsploit/handler.go
src/cloudsploit/main.go
src/cloudsploit/sqs.go

* handleErrorWithUpdateStatusはステータスの更新とエラーのラッピングという二つの責務を持っていたので、見通しをよくするために分割しました。責務に合わせてメソッド名も変更しています。
* スキャン用の設定ファイルが作成できない時にエラーを返すようにしました。

Resolve missing error in cloudsploit

---

src/guard-duty/client.go
src/guard-duty/guardduty.go
src/guard-duty/handler.go
src/guard-duty/main.go
src/guard-duty/sqs.go

src/guard-duty配下のエラーハンドリング改善しました。
* handleErrorWithUpdateStatusはステータスの更新とエラーのラッピングという二つの責務を持っていたので、見通しをよくするために分割しました。責務に合わせてメソッド名も変更しています。
* guardDutyClient.getGuardDutyの処理でlistFindings/getGuardDutyに失敗した時にエラーを返していませんでしたが、想定しているケース以外でエラーが発生すると想定しているスキャンができないためエラーを返すようにしています。その場合、ユーザがリトライしてもスキャンができない可能性があるため、通知ログを出してこちらで検知できるようにしています。（ #243 と同様の対応）

Resolve missing error in guard duty

---

src/portscan/client.go
src/portscan/handler.go
src/portscan/main.go
src/portscan/sqs.go

src/portscan配下のエラーハンドリング改善しました。
* handleErrorWithUpdateStatusはステータスの更新とエラーのラッピングという二つの責務を持っていたので、見通しをよくするために分割しました。責務に合わせてメソッド名も変更しています。
* 検知したfindingsをputする処理でエラーが発生した場合に、スキャン結果をエラーとしました。

Resolve missing error in portscan

---

src/portscan/portscan.go

https://github.com/ca-risken/aws/pull/249 で追加した影響確認用のログを削除して、portscanによるスキャンでエラーが発生した際に一律エラーを返すように変更します。
ここ一週間で該当のログはなかったので、運用への影響はないです。

Remove unused logging

---

src/portscan/go.mod
src/portscan/go.sum

common/pkg/portscanのScan失敗時に返すエラーの型を変更したのでその対応です。
エラーの型による個別のハンドリングは https://github.com/ca-risken/aws/pull/250 で変更済みなので、このPRはモジュールの更新のみです。

Upgrade common/pkg/portscan

---

src/cloudsploit/recommend.go

findingのタイプとrecommendの内容があってない箇所があったの修正します。
元ネタは↓です
- https://github.com/aquasecurity/cloudsploit/blob/master/plugins/aws/s3/bucketAllUsersAcl.js
- https://github.com/aquasecurity/cloudsploit/blob/master/plugins/aws/s3/bucketAllUsersPolicy.js
- https://github.com/aquasecurity/cloudsploit/blob/master/plugins/aws/s3/bucketEncryption.js

fix: recommend

---

src/access-analyzer/accessanalyzer.go
src/access-analyzer/handler.go
src/access-analyzer/main.go

AccessAnalyzerが月に1,2回程度の頻度で、AWS側の障害の影響を受けスキャンが不安定になることがあるため、RetryMaxAttemptで調整できるようにします。

add: retry param

---

src/guard-duty/guardduty.go
src/guard-duty/handler.go
src/guard-duty/main.go
src/portscan/handler.go
src/portscan/main.go
src/portscan/portscan.go

guarddutyとportscanにRetryMaxAttemptsの機構を導入します。
AWS側の一時的なエラーの影響を受けにくくする目的です。

add: control retry aws api

---

src/portscan/portscan.go

udp,tcp,all以外のIpProtocolが設定されている際にスキャン対象をallと同等に扱ってしまう問題を修正します

fix scan target protocol

---

go.mod
go.sum
pkg/adminchecker/handler.go
pkg/cloudsploit/handler.go
pkg/guardduty/handler.go
pkg/portscan/handler.go

ゼロクリア処理の条件を以下のように変更します. また、GuardDutyにもゼロクリア処理を追加します
- スキャン後に更新がなかったデータ（変更点）
- スコア > 0

fix: clear score finding

---

pkg/portscan/portscan.go
pkg/portscan/services_region.go

STSのエンドポイントを常にアクティブになるus-east-1へ変更します
lightsailで使用できないregionの確認をlightsailのAPIを叩く前に行うように修正します
lightsailの利用可能regionを追加しました

fix portscan

---

pkg/cloudsploit/config.go
pkg/cloudsploit/handler.go

設定済みのAssumeRoleやExternalIDでセッションが取得できなかった場合にエラーステータスに更新するようにします。

fix: credentials error handling

---

pkg/accessanalyzer/handler.go
pkg/adminchecker/handler.go
pkg/cloudsploit/cloudsploit.go
pkg/cloudsploit/handler.go
pkg/guardduty/handler.go
pkg/portscan/handler.go

cloudsploit scanでUNKNOWNステータスが合った場合にはscan detailに内容を記載するようにします。

fix: scan detail

---

dockers/cloudsploit/Dockerfile
pkg/cloudsploit/cloudsploit.go

cloudsploitを最新にアップデートします
- ビルド時間を計測する目的でbase-imageをpullする箇所を外します
- status_detailの値がmysqlのtext型65,535バイトを超過するケースがあったので、閾値を設定するようにしました

update: aws cloudsploit

---

pkg/accessanalyzer/handler.go

AWS のReadOnlyAccessポリシーを参考にAccessAnalyzerのReadAction判定のロジックを修正します（ReadActionのパターンを追加します）

fix: readonly check

---

pkg/adminchecker/admin_checker.go
pkg/cloudsploit/finding.go
pkg/cloudsploit/finding_test.go
pkg/common/util.go
pkg/common/util_test.go

ユーザが基本コントロール外であるマネージドIAMロールのFindingのスコアを下げます

ignore: managed iam roles

---

pkg/cloudsploit/finding.go
pkg/cloudsploit/finding_test.go

awsのarnの最大値は2048文字ですが、RISKENのDBのサイズに合わせてあまりにも長いリソース名は末尾をカットするようにしたいです。（オリジナルのARNはRawData（JSON）から参照できます。）

fix: get resource name

---

pkg/adminchecker/admin_checker.go
pkg/adminchecker/iam_policy.go

admin-checkerの出力内容を変更します。
- アタッチされているポリシーの詳細をJSONに追加します。
- カスタムポリシーやインラインポリシーはそのポリシードキュメントの内容の詳細も出力します。

fix: admin-checker policy

---

pkg/accessanalyzer/accessanalyzer.go

EFSをサポート対象外にします。
（アクセスアナライザーではポリシーの記述のみでパプリック判定されるが、前提として内部ネットワークのリーチャビリティリティが必須なため）

fix: ignore EFS

---

go.mod
pkg/accessanalyzer/accessanalyzer.go
pkg/accessanalyzer/handler.go

- リソースが存在しない場合のエラーハンドリングを追加
- AccessAnalyzerを委任アカウントで実行している場合に、個別のサービスの調査ができない（アクセスポリシーでの制御）ケースが発生したので、同じアカウントIDのセッションでAPI実行するように修正

fix: session & error handling

---

pkg/accessanalyzer/accessanalyzer.go

Conditionの深堀り調査でエラーが発生した場合に、スキャン自体をエラーにするのではなくWARNレベルに落とすことにします。（本体のスキャン結果は取り込む）

fix: error handling (WARN level)

---

.yamllint
cloudsploit.yaml
codebuild/multi-arch/install-go.sh
dockers/access-analyzer/Dockerfile
dockers/admin-checker/Dockerfile
dockers/cloudsploit/Dockerfile
dockers/guard-duty/Dockerfile
dockers/portscan/Dockerfile
go.mod
go.sum
pkg/cloudsploit/cloudsploit.go
pkg/cloudsploit/cloudsploit_test.go
pkg/cloudsploit/setting.go
pkg/cloudsploit/setting_test.go

cloudsploitのFinding除外設定を実装します。
slicesパッケージを使いたいのでGoもアプデします。

add: ignore findings

---

cloudsploit.yaml
pkg/cloudsploit/cloudsploit.go
pkg/cloudsploit/cloudsploit_test.go
pkg/cloudsploit/setting.go
pkg/cloudsploit/setting_test.go

以下の修正を行いました
-  AccessAnalyzerと重複しているプラグインはcloudsploit.yamlで除外
-  cloudsploit.yamlで `skipResourceNamePattern` オプションをサポート
- セキュリティグループの場合にはSG名を取得（skipResourceNamePatternの判定で利用できるようにするため）
- 既存のバグ修正（セキュリティグループかの判定がミスってた）

[CloudSploit] skipResourceNamePatternオプションのサポート

---

codebuild/multi-arch/buildspec-image.yml
codebuild/multi-arch/install-go.sh

CI環境でなぜか古いGoをインストールしてしまうので、明示的にインストールバージョンを指定できるようにしました（キャッシュなどの影響を受けづらくしました）

fix: go install

---

codebuild/multi-arch/buildspec-image.yml

goのインストールがうまくいかない時があるので、公式のランタイムバージョンを指定してみます（最新バージョンはサポートされないので注意ですが、RISKENのバージョンは対応されてます）

fix: install go version process

---

cloudsploit.yaml
cmd/cloudsploit/main.go
pkg/cloudsploit/cloudsploit.go
pkg/cloudsploit/cloudsploit_test.go
pkg/cloudsploit/handler.go

pluginごとのスキャンに処理を分割し、パラレルで実行するようにリファクタします。
主に以下のメリットがあります
- エラーになってしまうプラグインを除外できるようになる
- パフォーマンスが向上する（cloudsploitは10並列での処理なので、これ以上に設定することでスキャン速度が上がる）
また、今の固定バージョンだと以下のプラグインはエラーになるか、時間がかかりすぎる（数時間レベル）ことが分かったので除外します。
- GuardDuty/guarddutyMaster
- GuardDuty/guarddutyEnabled
- ElastiCache/reservedNodePaymentPending
- ElastiCache/elasticCacheClusterHasTags
- EC2/securityGroupsHasTags
- EC2/multipleSubnets
- CodeStar/codestarValidRepoProviders

refactor: parallel scan

---

pkg/cloudsploit/cloudsploit.go

タイムアウト1hではその前にコンテナが死んでしまう事象を確認しました。
つまり、タイムアウトがうまく効いてない印象なので少し短くします

fix: timeout

---

pkg/accessanalyzer/accessanalyzer.go
pkg/accessanalyzer/handler.go
pkg/accessanalyzer/handler_test.go

Lambdaがパブリックの場合でも、lambda:InvokeFunctionUrlのアクションのみの場合はスコアを下げます。
その他、不使用変数の削除などのリファクタリングしてます

add: lambda action

---

pkg/accessanalyzer/dlp.go

スキャン時間が大幅に上がってしまうことから、以下の制限をかけます。
- DLPスキャンの１ファイルあたりのサイズ上限を5MB
- サンプリングの最大ファイル数を5000に

feat: limit dlp scan files(size & num)
